// ------- Carpentry ------- //
craftsManager.addItem(new Item("Small Log", 70, "MateriaPrima"));
craftsManager.addItem(new Item("Heavy Log", 85, "MateriaPrima"));
craftsManager.addItem(new Item("Oil", 180, "Material"));
craftsManager.addItem(new Item("Coarse Thread", 480, "Material"));
craftsManager.addItem(new Item("Rough Plank", 125, "Material"));
craftsManager.addItem(new Item("T1 Oakwood Bow", 405, "Item"));
craftsManager.addItem(new Item("Sea Cured Leather", 580, "MateriaPrima"));
craftsManager.addItem(new Item("Refined Plank", 125, "Material"));
craftsManager.addItem(new Item("Craftman's Thread", 1220, "Material"));
craftsManager.addItem(new Item("T2 Viper's Bow", 1100, "Item"));
craftsManager.addItem(new Item("Sturdy String", 14000, "MateriaPrima"));
craftsManager.addItem(new Item("Treated Plank", 855, "Material"));
craftsManager.addItem(new Item("Fine Thread", 2550, "Material"));
craftsManager.addItem(new Item("T3 Black Ashe Bow", 4000, "Item"));
craftsManager.addItem(new Item("Copper Ingot", 185, "Material"));
craftsManager.addItem(new Item("T1 Wooden Bulwark", 135, "Item"));
craftsManager.addItem(new Item("Iron Ingot", 1750, "Material"));
craftsManager.addItem(new Item("T2 Sentinel Shield", 1050, "Item"));
craftsManager.addItem(new Item("Rough Steel Plate", 15000, "MateriaPrima"));
craftsManager.addItem(new Item("Steel Ingot", 2700, "Material"));
craftsManager.addItem(new Item("T3 Defender Bulwak", 18000, "Item"));
craftsManager.addItem(new Item("T1 Mystic Staff", 135, "Item"));
craftsManager.addItem(new Item("Troll Fang", 1480, "MateriaPrima"));
craftsManager.addItem(new Item("T2 Warlock Staff", 1050, "Item"));
craftsManager.addItem(new Item("Ambersprite Shard", 24000, "MateriaPrima"));
craftsManager.addItem(new Item("T3 Cultist Staff", 18000, "Item"));
craftsManager.addItem(new Item("Coarse Leather", 700, "Material"));
craftsManager.addItem(new Item("T1 Wooden Buckler", 100, "Item"));
craftsManager.addItem(new Item("Craftman's Leather", 1600, "Material"));
craftsManager.addItem(new Item("T2 Sturdy Buckler", 1000, "Item"));
craftsManager.addItem(new Item("Tanned Leather", 2900, "Material"));
craftsManager.addItem(new Item("T3 Marauder's Shield", 6000, "Item"));
craftsManager.addItem(new Item("T1 Knotted Sceptre", 150, "Item"));
craftsManager.addItem(new Item("T2 Tribal Sceptre", 490, "Item"));
craftsManager.addItem(new Item("T3 Serpent Sceptre", 4000, "Item"));

// ------- Blacksmithing ------- //
craftsManager.addItem(new Item("Copper Ore", 45, "MateriaPrima"));
craftsManager.addItem(new Item("Iron Ore", 320, "MateriaPrima"));
craftsManager.addItem(new Item("Coal", 170, "MateriaPrima"));
craftsManager.addItem(new Item("T1 Pliant Helmet", 780, "Item"));
craftsManager.addItem(new Item("T1 Pliant Armor", 695, "Item"));
craftsManager.addItem(new Item("T1 Pliant Legs", 759, "Item"));
craftsManager.addItem(new Item("T1 Pliant Boots", 770, "Item"));
craftsManager.addItem(new Item("T2 Crescent Helmet", 1600, "Item"));
craftsManager.addItem(new Item("T2 Crescent Armor", 1546, "Item"));
craftsManager.addItem(new Item("T2 Crescent Legs", 1899, "Item"));
craftsManager.addItem(new Item("T2 Crescent Boots", 2198, "Item"));
craftsManager.addItem(new Item("T3 Harbinger Helmet", 16900, "Item"));
craftsManager.addItem(new Item("T3 Harbinger Armor", 13000, "Item"));
craftsManager.addItem(new Item("T3 Harbinger Legs", 17900, "Item"));
craftsManager.addItem(new Item("T3 Harbinger Boots", 14700, "Item"));
craftsManager.addItem(new Item("Shell Fragment", 888, "MateriaPrima"));
craftsManager.addItem(new Item("T4 Enforcer Helmet", 0, "Item"));
craftsManager.addItem(new Item("T4 Enforcer Armor", 300000, "Item"));
craftsManager.addItem(new Item("T4 Enforcer Legs", 0, "Item"));
craftsManager.addItem(new Item("T4 Enforcer Boots", 0, "Item"));
craftsManager.addItem(new Item("Internal Padding", 25000, "MateriaPrima"));
craftsManager.addItem(new Item("T1 Shipbuilding Mallet", 370, "Item"));
craftsManager.addItem(new Item("T2 Crushing Hammer", 1150, "Item"));
craftsManager.addItem(new Item("T3 Punisher's Gavel", 25000, "Item"));
craftsManager.addItem(new Item("T4 Lawgiver's Warhammer", 0, "Item"));
craftsManager.addItem(new Item("T1 Burnished Greatsword", 350, "Item"));
craftsManager.addItem(new Item("T2 Valiant Greatsword", 1500, "Item"));
craftsManager.addItem(new Item("Thin Blade", 7500, "MateriaPrima"));
craftsManager.addItem(new Item("T3 Heroic Greatsword", 30000, "Item"));
craftsManager.addItem(new Item("T1 Skirmisher Blade", 370, "Item"));
craftsManager.addItem(new Item("T2 Swashbuckler Blade", 2450, "Item"));
craftsManager.addItem(new Item("Cunning Handle", 20500, "MateriaPrima"));
craftsManager.addItem(new Item("T3 Serpentine Blade", 25000, "Item"));
craftsManager.addItem(new Item("T4 Duelist's Companion", 550000, "Item"));
craftsManager.addItem(new Item("T1 Rough Sword", 400, "Item"));
craftsManager.addItem(new Item("T2 Warden's Sword", 1000, "Item"));
craftsManager.addItem(new Item("T3 Lawbreaker's Sword", 19000, "Item"));
craftsManager.addItem(new Item("T4 Guardian's Longsword", 120000, "Item"));
craftsManager.addItem(new Item("T1 Solid Mace", 550, "Item"));
craftsManager.addItem(new Item("T2 Studded Flail", 2000, "Item"));
craftsManager.addItem(new Item("T3 Shieldbreaker Flail", 25000, "Item"));
craftsManager.addItem(new Item("T1 Serrated Dagger", 200, "Item"));
craftsManager.addItem(new Item("T2 Noble Dagger", 1000, "Item"));
craftsManager.addItem(new Item("T3 Ice Dagger", 6500, "Item"));
craftsManager.addItem(new Item("T1 Wicked Axe", 200, "Item"));
craftsManager.addItem(new Item("T2 Marauder's Axe", 1500, "Item"));
craftsManager.addItem(new Item("Metallic Core", 15500, "MateriaPrima"));
craftsManager.addItem(new Item("T3 Dread Axe", 18000, "Item"));
craftsManager.addItem(new Item("T1 Rough Greataxe", 350, "Item"));
craftsManager.addItem(new Item("T2 Warrior's Greataxe", 1900, "Item"));
craftsManager.addItem(new Item("T3 Savage Battle Axe", 13000, "Item"));
craftsManager.addItem(new Item("T4 Hangman's Greataxe", 300000, "Item"));
// ------- Weaving ------- //
craftsManager.addItem(new Item("Hide", 400, "MateriaPrima"));
craftsManager.addItem(new Item("Cotton", 248, "MateriaPrima"));
craftsManager.addItem(new Item("Spool of Hair", 80, "MateriaPrima"));
craftsManager.addItem(new Item("Wool", 490, "MateriaPrima"));
craftsManager.addItem(new Item("T1 Loom Apprentice Helmet", 10500, "Item"));
craftsManager.addItem(new Item("T1 Loom Apprentice Armor", 11000, "Item"));
craftsManager.addItem(new Item("T1 Loom Apprentice Legs", 10000, "Item"));
craftsManager.addItem(new Item("T1 Loom Apprentice Boots", 8000, "Item"));
craftsManager.addItem(new Item("T1 Loom Apprentice Gloves", 13000, "Item"));
craftsManager.addItem(new Item("Craftman's Cloth", 1370, "Material"));
craftsManager.addItem(new Item("T2 Threadspinner Helmet", 55000, "Item"));
craftsManager.addItem(new Item("T2 Threadspinner Armor", 40000, "Item"));
craftsManager.addItem(new Item("T2 Threadspinner Legs", 40000, "Item"));
craftsManager.addItem(new Item("T2 Threadspinner Boots", 39000, "Item"));
craftsManager.addItem(new Item("T2 Threadspinner Gloves", 50000, "Item"));
craftsManager.addItem(new Item("Silk", 2500, "Material"));
craftsManager.addItem(new Item("T1 Apprentice Anvil Helmet", 11000, "Item"));
craftsManager.addItem(new Item("T1 Apprentice Anvil Armor", 11000, "Item"));
craftsManager.addItem(new Item("T1 Apprentice Anvil Legs", 12900, "Item"));
craftsManager.addItem(new Item("T1 Apprentice Anvil Boots", 10000, "Item"));
craftsManager.addItem(new Item("T1 Apprentice Anvil Bracers", 15000, "Item"));
craftsManager.addItem(new Item("T2 Silversmith Helmet", 65000, "Item"));
craftsManager.addItem(new Item("T2 Silversmith Armor", 65000, "Item"));
craftsManager.addItem(new Item("T2 Silversmith Legs", 65000, "Item"));
craftsManager.addItem(new Item("T2 Silversmith Boots", 60000, "Item"));
craftsManager.addItem(new Item("T2 Silversmith Bracers", 65000, "Item"));
craftsManager.addItem(new Item("T1 Fry Cook Helmet", 10000, "Item"));
craftsManager.addItem(new Item("T1 Fry Cook Armor", 11350, "Item"));
craftsManager.addItem(new Item("T1 Fry Cook Legs", 9500, "Item"));
craftsManager.addItem(new Item("T1 Fry Cook Boots", 7800, "Item"));
craftsManager.addItem(new Item("T1 Fry Cook Bracers", 18000, "Item"));
craftsManager.addItem(new Item("T2 Sous Chef Helmet", 60000, "Item"));
craftsManager.addItem(new Item("T2 Sous Chef Armor", 150000, "Item"));
craftsManager.addItem(new Item("T2 Sous Chef Legs", 60000, "Item"));
craftsManager.addItem(new Item("T2 Sous Chef Boots", 50000, "Item"));
craftsManager.addItem(new Item("T2 Sous Chef Bracers", 0, "Item"));
craftsManager.addItem(new Item("T1 Workshop Assistant Helmet", 13300, "Item"));
craftsManager.addItem(new Item("T1 Workshop Assistant Armor", 7800, "Item"));
craftsManager.addItem(new Item("T1 Workshop Assistant Legs", 11000, "Item"));
craftsManager.addItem(new Item("T1 Workshop Assistant Boots", 13000, "Item"));
craftsManager.addItem(new Item("T1 Workshop Assistant Gloves", 17800, "Item"));
craftsManager.addItem(new Item("T2 Woodworker Helmet", 60000, "Item"));
craftsManager.addItem(new Item("T2 Woodworker Armor", 70000, "Item"));
craftsManager.addItem(new Item("T2 Woodworker Legs", 50000, "Item"));
craftsManager.addItem(new Item("T2 Woodworker Boots", 60000, "Item"));
craftsManager.addItem(new Item("T2 Woodworker Gloves", 0, "Item"));
craftsManager.addItem(new Item("T1 Shadecloth Helmet", 389, "Item"));
craftsManager.addItem(new Item("T1 Shadecloth Armor", 130, "Item"));
craftsManager.addItem(new Item("T1 Shadecloth Legs", 400, "Item"));
craftsManager.addItem(new Item("T1 Shadecloth Boots", 200, "Item"));
craftsManager.addItem(new Item("Simple Cloth", 300, "Material"));
craftsManager.addItem(new Item("T2 Viper's Helmet", 1340, "Item"));
craftsManager.addItem(new Item("T2 Viper's Armor", 1000, "Item"));
craftsManager.addItem(new Item("T2 Viper's Legs", 1400, "Item"));
craftsManager.addItem(new Item("T2 Viper's Boots", 1790, "Item"));
craftsManager.addItem(new Item("T3 Profane Helmet", 8000, "Item"));
craftsManager.addItem(new Item("T3 Profane Armor", 7500, "Item"));
craftsManager.addItem(new Item("T3 Profane Legs", 8500, "Item"));
craftsManager.addItem(new Item("T3 Profane Boots", 8000, "Item"));
craftsManager.addItem(new Item("T4 Celestial Helmet", 200000, "Item"));
craftsManager.addItem(new Item("T4 Celestial Armor", 70000, "Item"));
craftsManager.addItem(new Item("T4 Celestial Legs", 0, "Item"));
craftsManager.addItem(new Item("T4 Celestial Boots", 0, "Item"));
craftsManager.addItem(new Item("Phantasmagorical Cloth", 9000, "MateriaPrima"));
craftsManager.addItem(new Item("T1 Hide Helmet", 365, "Item"));
craftsManager.addItem(new Item("T1 Hide Armor", 130, "Item"));
craftsManager.addItem(new Item("T1 Hide Legs", 400, "Item"));
craftsManager.addItem(new Item("T1 Hide Boots", 339, "Item"));
craftsManager.addItem(new Item("T2 Nomad Helmet", 1200, "Item"));
craftsManager.addItem(new Item("T2 Nomad Armor", 1300, "Item"));
craftsManager.addItem(new Item("T2 Nomad Legs", 1700, "Item"));
craftsManager.addItem(new Item("T2 Nomad Boots", 1700, "Item"));
craftsManager.addItem(new Item("T3 Bruiser Helmet", 4400, "Item"));
craftsManager.addItem(new Item("T3 Bruiser Armor", 3100, "Item"));
craftsManager.addItem(new Item("T3 Bruiser Legs", 6000, "Item"));
craftsManager.addItem(new Item("T3 Bruiser Boots", 8000, "Item"));
craftsManager.addItem(new Item("T4 Outlaw Helmet", 4400, "Item"));
craftsManager.addItem(new Item("T4 Outlaw Armor", 3100, "Item"));
craftsManager.addItem(new Item("T4 Outlaw Legs", 6000, "Item"));
craftsManager.addItem(new Item("T4 Outlaw Boots", 8000, "Item"));
craftsManager.addItem(new Item("Kaiman Scale", 6200, "MateriaPrima"));

// ------- Cooking ------- //
craftsManager.addItem(new Item("Potato", 50, "MateriaPrima"));
craftsManager.addItem(new Item("Corn", 195, "MateriaPrima"));
craftsManager.addItem(new Item("Orange Scales", 75, "MateriaPrima"));
craftsManager.addItem(new Item("Ground Flour", 100, "Material"));
craftsManager.addItem(new Item("Basic Seasoning", 20, "Material"));
craftsManager.addItem(new Item("Milk", 210, "MateriaPrima"));
craftsManager.addItem(new Item("Butter", 300, "Material"));
craftsManager.addItem(new Item("Honey", 145, "MateriaPrima"));
craftsManager.addItem(new Item("Egg", 120, "MateriaPrima"));
craftsManager.addItem(new Item("Gourmet Seasoning", 285, "Material"));
craftsManager.addItem(new Item("Wheat", 120, "MateriaPrima"));
craftsManager.addItem(new Item("Apple", 445, "MateriaPrima"));
craftsManager.addItem(new Item("Brewer Yeast", 175, "Material"));
craftsManager.addItem(new Item("Grape", 115, "MateriaPrima"));
craftsManager.addItem(new Item("Orange", 870, "MateriaPrima"));
craftsManager.addItem(new Item("Blueberry", 30, "MateriaPrima"));
craftsManager.addItem(new Item("Watermelon", 0, "MateriaPrima"));
craftsManager.addItem(new Item("Pumpkin", 2000, "MateriaPrima"));
craftsManager.addItem(new Item("Carrot", 70, "MateriaPrima"));
craftsManager.addItem(new Item("Garlic", 8000, "MateriaPrima"));
craftsManager.addItem(new Item("Shank", 40, "MateriaPrima"));
craftsManager.addItem(new Item("Beef", 130, "MateriaPrima"));
craftsManager.addItem(new Item("Cabbage", 165, "MateriaPrima"));
craftsManager.addItem(new Item("Chicken", 395, "MateriaPrima"));
craftsManager.addItem(new Item("Bean", 100, "MateriaPrima"));
craftsManager.addItem(new Item("Fish Roe", 58, "MateriaPrima"));
craftsManager.addItem(new Item("Seafood Seadoning", 70, "Material"));
craftsManager.addItem(new Item("Strawberry", 95, "MateriaPrima"));
craftsManager.addItem(new Item("Brocolli", 0, "MateriaPrima"));
craftsManager.addItem(new Item("Salt", 100, "MateriaPrima"));
craftsManager.addItem(new Item("Onion", 230, "MateriaPrima"));
craftsManager.addItem(new Item("Three-Leaf Clover", 50, "MateriaPrima"));
